"""Nueva migración limpia

Revision ID: 1beaae91e44c
Revises: a7bfdeb049e2
Create Date: 2025-03-25 20:49:44.236724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1beaae91e44c'
down_revision = 'a7bfdeb049e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('apellidos',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('telefono',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('direccion',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('ciudad',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('pais',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('foto',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('foto',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('pais',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('ciudad',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('direccion',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('telefono',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('apellidos',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###
