"""Added role field to User model

Revision ID: 664e53f6ca36
Revises: f080d6f184e1
Create Date: 2025-03-16 23:20:17.615909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '664e53f6ca36'
down_revision = 'f080d6f184e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.NUMERIC(), nullable=True))

    # ### end Alembic commands ###
